---
title: "Data_Replication_gpelose_Workbook1"
author: "Greg Pelose"
date: "12/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Introduction

##Backgroung Informaiton
  

Getting data from excel into R
```{r}
install.packages("readxl")
```
```{r}
library(readxl)
```


Figure 1

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
```


```{r}
Figure_1 <- read_excel("individual_project.xlsx", 
    sheet = "GP-Fig.1")
summary(Figure_1)
```


```{r,fig.width=4,fig.height=4}
ggplot(data=Figure_1,aes(x=MP_type,y=MP_count))+geom_boxplot()+xlab("Plastic Type")+ylab("no. plastics per polyp")+scale_y_continuous(lim=c(0,100),breaks=c(0,20,40,60,80,100))+theme_classic()+annotate("text", x = "Beads", y = 35, label = "A")+annotate("text", x = "Fibers", y = 100, label = "B")+annotate("text", x = "Misc", y = 30, label = "A")
```

Questions about figure 1:
I cannot figure out how to get the A, A, B above the image
I cannot figure out how to change the values of the y-axis

```{r}
x_value <- "Figure_1$beads, Figure_1$fibers, Figure_1$Mis"
```


Attempting to create in ggplot

```{r}
Plot_1 <-ggplot(Figure_1, aes(x= "x_value", y="Figure_1$Observations"))
p <- Plot_1 + geom_boxplot()
p
```

Questioins:
How do I make this work

#Figure 2

```{r}
Figure_2 <- read_excel("individual_project.xlsx", 
    sheet = "GP-Fig.2")
summary(Figure_2)
names(Figure_2)
```
```{r}
top <- Figure_2$Top 
middle <- Figure_2$Middle
Bottom <- Figure_2$Bottom
top
```

```{r}
plot_2 <- ggplot(Figure_2, aes(x=colony,y=MP_ingested))
plot_2 + geom_histogram(stat="identity",aes(fill=location))+theme_classic()+scale_fill_manual()
```



```{r}
Sheet_2_Fig_2 <- read_excel("individual_project.xlsx", 
    sheet = "sheet 2 again", col_types = c("numeric", 
        "numeric", "numeric"))
View(individual_project)
summary("Sheet_2_Fig_2")
names("Sheet_2_Fig_2")
```


```{r}
Plot_2 <- ggplot(Figure_2, aes(x=, y=))
plot_2 + geom_bar()
```


#Figure 3

```{r}
Figure_3 <- read_excel("individual_project.xlsx", 
     sheet = "GP-Fig.3")
summary(Figure_3)
boxplot(Figure_3, ylab="particles consumed (mm^3)")
```


#Figure 4






#Figure 5

```{r}
Figure_5 <- read_excel("individual_project.xlsx", 
    sheet = "GP-Fig.5")
summary(Figure_5)
plot(Figure_5)
```


